networks:
  usuariosapp-network:
    driver: bridge

services:

 usuariosapp:
    container_name: usuariosapp-api
    build:
       context: .
       dockerfile: UsuariosApp.API/Dockerfile
    ports:
       - "8081:8080"
    networks:
      - usuariosapp-network
    depends_on:
       - sqlserver

 sqlserver:
    container_name: usuariosapp-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "Coti@2025"
      ACCEPT_EULA: "Y"
    networks:
      - usuariosapp-network
    restart: always
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
